// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD303WJZDj6neH-y7NM4gR_XTycpw5hEk',
    appId: '1:159725841533:web:7eb6e4338eac02f8afd514',
    messagingSenderId: '159725841533',
    projectId: 'masalinressami-5fbe7',
    authDomain: 'masalinressami-5fbe7.firebaseapp.com',
    storageBucket: 'masalinressami-5fbe7.appspot.com',
    measurementId: 'G-6KB7PMYER3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7ov4wF8Oud8ua8pvVoVOStslDYrUpss',
    appId: '1:159725841533:android:af17d90b3a1c0cbdafd514',
    messagingSenderId: '159725841533',
    projectId: 'masalinressami-5fbe7',
    storageBucket: 'masalinressami-5fbe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjxyWo-Ti0twxsGO22okstz_eSiiFfK6A',
    appId: '1:159725841533:ios:0249b2934def8c99afd514',
    messagingSenderId: '159725841533',
    projectId: 'masalinressami-5fbe7',
    storageBucket: 'masalinressami-5fbe7.appspot.com',
    iosBundleId: 'com.example.masalinRessami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjxyWo-Ti0twxsGO22okstz_eSiiFfK6A',
    appId: '1:159725841533:ios:0249b2934def8c99afd514',
    messagingSenderId: '159725841533',
    projectId: 'masalinressami-5fbe7',
    storageBucket: 'masalinressami-5fbe7.appspot.com',
    iosBundleId: 'com.example.masalinRessami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD303WJZDj6neH-y7NM4gR_XTycpw5hEk',
    appId: '1:159725841533:web:d2597f9217417f8eafd514',
    messagingSenderId: '159725841533',
    projectId: 'masalinressami-5fbe7',
    authDomain: 'masalinressami-5fbe7.firebaseapp.com',
    storageBucket: 'masalinressami-5fbe7.appspot.com',
    measurementId: 'G-JC6N25S1PN',
  );
}
